MedicalRecords/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('home.urls','home'),namespace='home')),
    path('citas/',include(('citas.urls','citas'),namespace='citas')),
    path('pacientes/',include(('pacientes.urls','pacientes'),namespace='pacientes')),
]

citas/urls.py
from django.urls import path
from citas.views import ListarCitas, InsertarCita, EditarCita, BorrarCita

urlpatterns=[
    path('citas', ListarCitas.as_view(), name='citas_list'),
    path('citas/new', InsertarCita.as_view(), name='insertar_cita'),
    path('citas/edit<int:pk>', EditarCita.as_view(), name='editar_cita'),
    path('citas/delete<int:pk>', BorrarCita.as_view(), name='borrar_cita'),
]

home/urls.py
from django.contrib import admin
from django.urls import include, path
from home.views import Home 
urlpatterns=[
    path('',Home.as_view(),name='home'),
]

pacientes/urls.py
from django.urls import path
from pacientes.views import ListarPacientes, InsertarPaciente, EditarPaciente, BorrarPaciente

urlpatterns=[
    path('pacientes', ListarPacientes.as_view(), name='pacientes_list'),
    path('pacientes/new', InsertarPaciente.as_view(), name='insertar_paciente'),
    path('pacientes/edit<int:pk>', EditarPaciente.as_view(), name='editar_paciente'),
    path('pacientes/delete<int:pk>', BorrarPaciente.as_view(), name='borrar_paciente'),
]

citas/models.py
from django.db import models

# Create your models here.
class Cita(models.Model):
    horaCita=models.TimeField()
    fechaCita=models.DateField()
    medico=models.CharField(max_length=100,)
    especialidad=models.CharField(max_length=100,)
    unidadAtencion=models.CharField(max_length=100,)
    IDPaciente=models.CharField(max_length=100,)
    def __str__(self):
        return '{}'.format(self.medico)
    def save(self):
        super(Cita, self).save()

    class Meta:
        verbose_name_plural="Citas"

home/models.py
from django.db import models

# Create your models here.

pacientes/models.py
from django.db import models

# Create your models here.
class Paciente(models.Model):
   
    nombre=models.CharField(max_length=100,)
    edad=models.CharField(max_length=100,)
    ciudad=models.CharField(max_length=100,)
    EPS=models.CharField(max_length=100,)
    def __str__(self):
        return '{}'.format(self.nombre)
    def save(self):
        super(Paciente, self).save()

    class Meta:
        verbose_name_plural="Pacientes"

citas/forms.py
from django import forms
from citas.models import Cita
class CitaForm(forms.ModelForm):
    class Meta: 
        model=Cita
        fields=['medico','especialidad','unidadAtencion','IDPaciente','fechaCita','horaCita']
        labels={'medico':'Medico','especialidad': 'Especialidad','unidadAtencion':'Unidad de Atencion ','IDPaciente':'ID del paciente',
        'fechaCita':'Fecha de la Cita', 'horaCita':'Hora'}
        widget={'medico': forms.TextInput()}

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

pacientes/forms.py
from django import forms
from pacientes.models import Paciente
class PacienteForm(forms.ModelForm):
    class Meta: 
        model=Paciente
        fields=['nombre','edad','ciudad','EPS']
        labels={'nombre':'Nombre del paciente', 'Edad':'Edad','Ciudad':'Ciudad','EPS':'EPS'}
        widget={'nombre': forms.TextInput()}

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

citas/views.py
from django.shortcuts import render
from citas.models import Cita
from django.views import generic
from citas.forms import CitaForm
from django.urls import reverse_lazy
# Create your views here.
class ListarCitas(generic.ListView):
    model=Cita
    template_name="citas/listar_citas.html"
    context_object_name="obj"
class InsertarCita(generic.CreateView):
    model=Cita
    template_name="citas/insertar_cita.html"
    context_object_name="obj"
    form_class=CitaForm
    success_url=reverse_lazy("citas:citas_list")
class EditarCita(generic.UpdateView):
    model=Cita
    template_name="citas/insertar_cita.html"
    context_object_name="obj"
    form_class=CitaForm
    success_url=reverse_lazy("citas:citas_list")
class BorrarCita(generic.DeleteView):
    model=Cita
    template_name="citas/borrar_cita.html"
    context_object_name="obj"
    form_class=CitaForm
    success_url=reverse_lazy("citas:citas_list")

home/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse
# Create your views here.
class Home(generic.TemplateView):
    template_name="home/home.html"

pacientes/views.py
from django.shortcuts import render
from  pacientes.models import Paciente
from django.views import generic
from pacientes.forms import PacienteForm
from django.urls import reverse_lazy

# Create your views here.
class ListarPacientes(generic.ListView):
    model=Paciente
    template_name="pacientes/listar_pacientes.html"
    context_object_name="obj"
class InsertarPaciente(generic.CreateView):
    model=Paciente
    template_name="pacientes/insertar_paciente.html"
    context_object_name="obj"
    form_class=PacienteForm
    success_url=reverse_lazy("pacientes:pacientes_list")
class EditarPaciente(generic.UpdateView):
    model=Paciente
    template_name="pacientes/editar_paciente.html"
    context_object_name="obj"
    form_class=PacienteForm
    success_url=reverse_lazy("pacientes:pacientes_list")
class BorrarPaciente(generic.DeleteView):
    model=Paciente
    template_name="pacientes/borrar_paciente.html"
    context_object_name="obj"
    form_class=PacienteForm
    success_url=reverse_lazy("pacientes:pacientes_list")

citas/templates/citas/borrar_cita.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="post">
    <div class="panel panel-default">
        <div class="panel-heading">
            Eliminar Cita
        </div>
        <div class ="panel-body">
            {% csrf_token %}
            <div class="alert alert-succes">
                Eliminar {{obj.medico}}
            </div>
            <button type="submit" class="btn btn-danger">
                <span class="fa fa-delete">Eliminar</span>
            </button>
            <a href="{% url 'citas:citas_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Regresar</a>
        </div>
    </div>
</div>
</form>
{% endblock contenido %}

citas/templates/citas/insertar_cita.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="post">
    <div class="panel-body">
     
    {%csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-success">
        <span class="fa fa-save">
            Guardar Cita
        </span>
    </button>
    <a href="{% url 'citas:citas_list' %}" class="btn btn-danger"><span class="fa fa-undo">Regresar a tus citas</span></a>    
    </div>
</form>
{% endblock contenido %}

citas/templates/citas/listar_citas.html
{% extends 'base/base.html' %}
{% block contenido %}
<h1>
    <Body background="static\clc.jpg " width="20" height="10"></body>
    </h1>
<table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
    <thead>
        <tr>
            <th>ID Cita</th>
            <th>Medico </th>
            <th>Especialidad</th>
            <th>Unidad de Atencion</th>
            <th>ID Paciente</th>
            <th>Fecha</th>
            <th>Hora</th>
            <th>Acciones con Citas</th>
        </tr>
    </thead>
    <tbody>
        {% for item in obj %}
        <tr>
            <td>
                {{item.id}}
            </td>
            <td>
                {{item.medico}}
            </td>
            <td>
                {{item.especialidad}}
            </td>
            <td>
                {{item.unidadAtencion}}
            </td>
            <td>
                {{item.IDPaciente}}
            </td>
            <td>
                {{item.fechaCita}}
            </td>
            <td>
                {{item.horaCita}}
            </td>
            <td>
            <a href="{% url 'citas:editar_cita' item.id %}" class="btn btn-primary btn-circle"><span class="fa fa-edit"></span>Editar Cita</a> 
            <a href="{% url 'citas:borrar_cita' item.id %}" class="btn btn-danger btn-circle"><span class="fa fa-trash "></span>Eliminar Cita</a> 
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock contenido %}

home/templates/home/home.html
{% extends 'base/base.html' %}
{% block head_title %}
Medical Records
{%endblock head_title %}
{% block contenido %}
<h1>
<Body background="static\Hosp.jpg " width="20" height="10"></body>
</h1>
{%endblock contenido%}

pacientes/templates/pacientes/borrar_paciente.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="post">
    <div class="panel panel-default">
        <div class="panel-heading">
            Eliminar Paciente
        </div>
        <div class ="panel-body">
            {% csrf_token %}
            <div class="alert alert-succes">
                Eliminar {{obj.nombre}}
            </div>
            <button type="submit" class="btn btn-danger">
                <span class="fa fa-delete">Eliminar</span>
            </button>
            <a href="{% url 'pacientes:pacientes_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Regresar a pacientes</a>
        </div>
    </div>
</div>
</form>
{% endblock contenido %}

pacientes/templates/pacientes/insertar_paciente.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="post">
    <div class="panel-body">
     
    {%csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-success">
        <span class="fa fa-save">
            Guardar Paciente
        </span>
    </button>
    <a href="{% url 'pacientes:pacientes_list' %}" class="btn btn-danger"><span class="fa fa-undo">Regresar a tus pacientes</span></a>    
    </div>
</form>
{% endblock contenido %}

pacientes/templates/pacientes/listar_pacientes.html
{% extends 'base/base.html' %}
{% block contenido %}
<table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
    <thead>
        <tr>
            <th>ID Paciente</th>
            <th>Nombre</th>
            <th>Edad</th>
            <th>Ciudad</th>
            <th>EPS</th>
            <th>Observaciones</th>
        </tr>
    </thead>
    <tbody>
        {% for item in obj %}
        <tr>
            <td>
                {{item.id}}
            </td>
            <td>
                {{item.nombre}}
            </td>
            <td>
                {{item.edad}}
            </td>
            <td>
                {{item.ciudad}}
            </td>
            <td>
                {{item.EPS}}
            </td>
            <td>
            <a href="{% url 'pacientes:editar_paciente' item.id %}" class ="btn btn-primary btn-circle"><span class="fa fa-edit"></span>Editar Paciente</a>
            <a href="{% url 'pacientes:borrar_paciente' item.id %}" class ="btn btn-danger btn-circle"><span class="fa fa-trash"></span>Eliminar Paciente</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock contenido %}

templates/base/base.html
<!doctype html>
<html lang="es">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">


  <title> {% block head_title %}
    Medical Records
    {% endblock head_title %}
  </title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/navbars/">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Bootstrap core CSS -->
  <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="navbar.css" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
   
</head>

<body >


  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

      <div class="collapse navbar-collapse" id="navbarsExample07">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home:home' %}">Inicio <span class="sr-only">(current)</span></a>
          </li>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown07" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">Citas</a>
            <div class="dropdown-menu" aria-labelledby="dropdown07">
              <a class="dropdown-item" href="{% url 'citas:citas_list' %}">Listar Citas</a>
              <a class="dropdown-item" href="{% url 'citas:insertar_cita' %}">Asignar Cita</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown07" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">Pacientes</a>
            <div class="dropdown-menu" aria-labelledby="dropdown07">
              <a class="dropdown-item" href="{% url 'pacientes:pacientes_list' %}">Listar Pacientes</a>
              <a class="dropdown-item" href="{% url 'pacientes:insertar_paciente' %}">Registrar Paciente</a>
            </div>
        </ul>
      </div>
    </div>
  </nav>
  {% block contenido %}Se puede cambiar{% endblock contenido %}




  <!-- Bootstrap core JavaScript
    ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
</body>


</html>